### ISSUE TITLE
Deprecated code in NHST.jl leads to errors- update needed (proposed below)

### ISSUE THREAD

**Issue by ghost** [johnmyleswhite/NHST.jl#2]
Examplary errors presented below:
julia> using NHST
WARNING: load is deprecated, use require instead.
 in include_from_node1 at loading.jl:91
julia> chi_squared_test([1,2,8,200])
ERROR: in chi_squared_test: ccdf not defined
 in chi_squared_test at /home/biosmooth/.julia/NHST/src/chi_squared_test.jl:15
 in chi_squared_test at /home/biosmooth/.julia/NHST/src/chi_squared_test.jl:30

Please find updated version of NHST.jl code below:
using Distributions

module NHST

  using Base
  using Distributions

  export binom_p_value, binom_test, chi_squared_test, t_test

  include("types.jl")
  include("binom_test.jl")
  include("chi_squared_test.jl")
  include("t_test.jl")

end

**Comment by johnmyleswhite** [comment]
Closed by 46830ea06c55b6ba570443c376735e9f81c7d82f
