### ISSUE TITLE
Is Chisq really two-sided?

### ISSUE THREAD

**Issue by andrewcooke** [johnmyleswhite/NHST.jl#5]
Chisq is normally used as a one-sided test. I think your routines correspond to normal use.  But it is labelled as two-sided.

**Comment by andrewcooke** [comment]
Oh.  I guess if you look at it as [200,0] v [0,200] it's two-sided.  On the other hand, if you look at it as fitting, it doesn't detect "too good' a fit.  I am probably confused.  Sorry.

**Comment by andrewcooke** [comment]
I am not the only one confused - http://stats.stackexchange.com/questions/22347/chi-squared-always-a-one-sided-test

**Comment by johnmyleswhite** [comment]
I think the confusion is that the concept of two-sidedness doesn't really make sense when asking about the CDF of a strictly non-negative quantity. We should probably come up with another classification for this at some point.
